export const englishAuctionAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "error", inputs: [], name: "EnforcedPause" },
  { type: "error", inputs: [], name: "ExpectedPause" },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "OwnableInvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "OwnableUnauthorizedAccount",
  },
  { type: "error", inputs: [], name: "ReentrancyGuardReentrantCall" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "auctionId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "timestamp",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "AuctionCancelled",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "auctionId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "seller",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "nftContract",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "nftId",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "startingBid",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "duration",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "createdAt",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "AuctionCreated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "auctionId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "winner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "timestamp",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      { name: "hadBids", internalType: "bool", type: "bool", indexed: false },
    ],
    name: "AuctionEnded",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "auctionId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "oldEndTime",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "newEndTime",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "AuctionExtended",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "auctionId",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "AuctionStartStarted",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "auctionId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "startTime",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "endTime",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "AuctionStarted",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "auctionId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "bidder",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "timestamp",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "previousBidder",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "previousBid",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "BidPlaced",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "auctionId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "bidder",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "timestamp",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "BidWithdrawn",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "oldMinBidIncrementPercentage",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "newMinBidIncrementPercentage",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MinBidIncrementPercentageUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "auctionId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "seller",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "first", internalType: "bool", type: "bool", indexed: false },
      { name: "second", internalType: "bool", type: "bool", indexed: false },
      { name: "third", internalType: "bool", type: "bool", indexed: false },
    ],
    name: "TestEvent",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "oldTimeBuffer",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "newTimeBuffer",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "TimeBufferUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "auctionBidInfos",
    outputs: [
      { name: "highestBidder", internalType: "address", type: "address" },
      { name: "highestBid", internalType: "uint256", type: "uint256" },
      { name: "bidsCount", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "address", type: "address" },
    ],
    name: "auctionBids",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "auctionCores",
    outputs: [
      { name: "nftContract", internalType: "address", type: "address" },
      { name: "nftId", internalType: "uint256", type: "uint256" },
      { name: "seller", internalType: "address payable", type: "address" },
      { name: "startingBid", internalType: "uint256", type: "uint256" },
      { name: "endAt", internalType: "uint256", type: "uint256" },
      { name: "started", internalType: "bool", type: "bool" },
      { name: "ended", internalType: "bool", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "auctionIdCounter",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "auctionTimestamps",
    outputs: [
      { name: "createdAt", internalType: "uint256", type: "uint256" },
      { name: "startedAt", internalType: "uint256", type: "uint256" },
      { name: "endedAt", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_auctionId", internalType: "uint256", type: "uint256" }],
    name: "cancelAuction",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_nftContract", internalType: "address", type: "address" },
      { name: "_nftId", internalType: "uint256", type: "uint256" },
      { name: "_startingBid", internalType: "uint256", type: "uint256" },
      { name: "_duration", internalType: "uint256", type: "uint256" },
    ],
    name: "createAuction",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_auctionId", internalType: "uint256", type: "uint256" }],
    name: "endAuction",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_startIndex", internalType: "uint256", type: "uint256" },
      { name: "_count", internalType: "uint256", type: "uint256" },
    ],
    name: "getActiveAuctions",
    outputs: [{ name: "", internalType: "uint256[]", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_auctionId", internalType: "uint256", type: "uint256" }],
    name: "getAuctionBidInfo",
    outputs: [
      { name: "highestBidder", internalType: "address", type: "address" },
      { name: "highestBid", internalType: "uint256", type: "uint256" },
      { name: "bidsCount", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_auctionId", internalType: "uint256", type: "uint256" }],
    name: "getAuctionCore",
    outputs: [
      { name: "nftContract", internalType: "address", type: "address" },
      { name: "nftId", internalType: "uint256", type: "uint256" },
      { name: "seller", internalType: "address", type: "address" },
      { name: "startingBid", internalType: "uint256", type: "uint256" },
      { name: "endAt", internalType: "uint256", type: "uint256" },
      { name: "started", internalType: "bool", type: "bool" },
      { name: "ended", internalType: "bool", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_auctionId", internalType: "uint256", type: "uint256" }],
    name: "getAuctionTimestamps",
    outputs: [
      { name: "createdAt", internalType: "uint256", type: "uint256" },
      { name: "startedAt", internalType: "uint256", type: "uint256" },
      { name: "endedAt", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "getTotalAuctions",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_user", internalType: "address", type: "address" }],
    name: "getUserAuctions",
    outputs: [{ name: "", internalType: "uint256[]", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_auctionId", internalType: "uint256", type: "uint256" },
      { name: "_user", internalType: "address", type: "address" },
    ],
    name: "getUserBidAmount",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_user", internalType: "address", type: "address" }],
    name: "getUserBids",
    outputs: [{ name: "", internalType: "uint256[]", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "minBidIncrementPercentage",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC721Received",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "paused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_auctionId", internalType: "uint256", type: "uint256" }],
    name: "placeBid",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_minBidIncrementPercentage",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "setMinBidIncrementPercentage",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_timeBuffer", internalType: "uint256", type: "uint256" }],
    name: "setTimeBuffer",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_auctionId", internalType: "uint256", type: "uint256" },
      { name: "_duration", internalType: "uint256", type: "uint256" },
    ],
    name: "startAuction",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "timeBuffer",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "userAuctions",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "userBids",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_auctionId", internalType: "uint256", type: "uint256" }],
    name: "withdrawBid",
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;
